const CONFIG = {
    introTitle: 'Hi, chào cậu ! Mình là  Mạnh Hùng...',
    introDesc: ` (∪ ◡ ∪) ...Vào nghe nhạc nha bạn iu... (*^ -^*) `,
    btnIntro: ' Ok, lets go! ',
    title: ' Đằng ấy có thấy đẹp không? ',
    desc: ' Nếu mà nói dối là đằng ấy sẽ ế suốt đời😂... ',
    btnYes: ' Có ',
    btnNo: ' Không ',
    question: ' Thật hả ? ',
    btnReply: ' Send to Mạnh Hùng ',
    reply: ' Thật mà...hjhj... Tớ mà nói điêu thì tớ làm chó😂... ',
    mess: ' 💓💓💓 ',
    messDesc: ' Mình biết mà .hiihaa...!',
    btnAccept: ' Thả tym...🫰🫰🫰 ',
    messLink: '',
}
