const CONFIG = {
    introTitle: 'Hi, chào cậu ! Mình là  Mạnh Hùng...',
    introDesc: ` (∪ ◡ ∪) ...NMH... (*^ -^*) `,
    btnIntro: ' Ok, lest go! ',
    title: ' Đằng ấy có thấy đẹp không? ',
    desc: ' Nếu mà nói dối là đằng ấy sẽ ế suốt đời😂... ',
    btnYes: ' Có ',
    btnNo: ' Không ',
    question: ' Thật hả ? ',
    btnReply: ' Send to Xấu zai từ bé ',
    reply: ' Thật mà...hjhj... Tớ mà nói điêu thì tớ làm chó😂... ',
    mess: ' 👍 ',
    messDesc: ' Yêu thế nhờ...! ',
    btnAccept: ' Mình biết mà .hiihaa ',
    messLink: '',
}
